sudo: required
services:
  - docker

before_install:
  - docker build -t zz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zz/react-test npm test

after_success:
  - docker build -t nnnightingale/multi-client ./client
  - docker build -t nnnightingale/multi-nginx ./nginx
  - docker build -t nnnightingale/multi-server ./server
  - docker build -t nnnightingale/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #  Take images and push to the docker hub
  - docker push nnnightingale/multi-client
  - docker push nnnightingale/multi-nginx
  - docker push nnnightingale/multi-server
  - docker push nnnightingale/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-020611481479'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY