sudo: required
services:
  - docker

before_install:
  - docker build -t zz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zz/react-test npm test

after_success:
  - docker build -t zz/multi-client ./client
  - docker build -t zz/multi-nginx ./nginx
  - docker build -t zz/multi-server ./server
  - docker build -t zz/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #  Take images and push to the docker hub
  - docker push zz/multi-client
  - docker push zz/multi-nginx
  - docker push zz/multi-server
  - docker push zz/multi-worker


